name: publish-synopsys-extension

on:
  workflow_dispatch:

jobs:
  publish-synopsys-extension:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Rebuild the dist/ directory
        uses: ./.github/workflows/check-dist.yml
