name: publish-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  publish-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: publish-extension
        env:
          PUBLISHER_NAME: ${{ secrets.PUBLISHER_NAME }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          MAJOR: 1
          MINOR: 0
          PATCH: $[counter($MINOR, 0)]
          VERSION: $MAJOR.$MINOR.$PATCH
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
          commit_message: ${{ github.event.head_commit.message }}
        run: |
          name="Synopsys-security-scan"
          echo $name
          echo "EXTENSION_NAME=$name" >> build.env
          vss_extension_dev=$(cat vss-extension-dev.json)
          vss_extension_dev=$(echo $vss_extension_dev | jq ".id = \"$name\"")
          vss_extension_dev=$(echo $vss_extension_dev | jq ".name = \"$name\"")
          azure_extension_version=$(echo $vss_extension_dev | jq -r '.version')
          echo $azure_extension_version
          major=$(echo $azure_extension_version | awk -F. '{print $1}')
          minor=$(echo $azure_extension_version | awk -F. '{print $2}')
          patch=$(echo $azure_extension_version | awk -F. '{print $3}')
          echo $major
          echo $minor
          echo $patch
          echo $commit_message
          echo "title=$(git log --format=%B -n 1 HEAD | head -n 1)"
          commit=$(echo "$commit_message" | awk -F: '{print $1}') 
          if [[ "$commit" == "BREAKING CHANGE" ]]; then
             version=$((major+1)).0.0
          elif [[ "$commit" == "feat" ]]; then
             version=$major.$((minor+1)).0
          elif [[ "$commit" == "fix" ]]; then
             version=$major.$minor.$((patch+1))
          fi
          echo $version
          jq --arg version "$version" '.version = $version' vss-extension-dev.json > vss-extension-dev.json.tmp && mv vss-extension-dev.json.tmp vss-extension-dev.json
          cat vss-extension-dev.json
          echo "AZURE_EXTENSION_VERSION=$azure_extension_version" >> build.env
          npm i -g tfx-cli
#          tfx extension publish --publisher TestCIPub  --manifest-globs vss-extension-dev.json --token ${USER_TOKEN}
      #          echo $version
#           rm vss-extension-dev.json
#           echo $vss_extension > vss-extension-dev.json
#           echo $vss_extension > vss-extension.json
#           cat vss-extension-dev.json
#           cat vss-extension.json
#           cd synopsys-task
#           task_json=$(cat task.json)
#           task_json=$(echo $task_json | jq ".name = \"$name\"")
#           task_json=$(echo $task_json | jq ".id = \"$uuid\"")
#           rm task.json
#           npm install
#           npm run all
#           rm -rf node_modules
#           echo $task_json > task.json
#           cat task.json
#           cd ..


      # - name: Install dependencies
      #   run: cd synopsys-task && npm ci

      # - name: Unit Test Cases
      #   id: unit-test-cases
      #   shell: bash
      #   run: |
      #     cd synopsys-task && npm run test
      #     coverageFile="coverage/index.html"

      #     ### fetching line coverage from coverage/index.html file
      #     coverageSpan=$(grep -B 1 '<span class="quiet">Lines</span>' $coverageFile | head -n 1)
      #     coverageHtml=$(echo "$coverageSpan" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')
      #     coverageInPercent=$(echo $coverageHtml | sed -n 's/.*<span class="strong">\([0-9.]*%\).*/\1/p' | tr -d ' ')
      #     echo "Line Coverage: $coverageInPercent"

      #     ### remove percentage sign from coverageInPercent and convert to a floatin-point number 
      #     coverageValue=$(echo "$coverageInPercent" | tr -d '%' | sed 's/,/./g')
      #     ### check if the coverage is below 90%
      #     if [[ $coverageValue < 90 ]]; then
      #         echo "##[error]Line coverage is below 90%"
      #         exit 1
      #     fi
